name: Pack Contoso University Core

on:
  push:
    paths:
      - DevOps_Workshop/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: DevOps_Workshop.zip
          solution-folder: DevOps_Workshop
          solution-type: Both
      - uses: actions/upload-artifact@v2
        with:
          name: packed-solution
          path: DevOps_Workshop/
